config/routes.rb
Rails.application.routes.draw do
  get 'polls/user'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  mount Attachinary::Engine => "/attachinary"
  mount ActionCable.server => '/cable'
  root to: 'polls#index'

  resources :categories
  resources :polls do
    resources :reviews, only: [ :new, :create ]
  end
  resources :responses do
    resources :votes
  end
  resources :follows, only: [:new, :create]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :polls
  has_attachment :picture
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @category_polls = @category.polls
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class= "container-fluid">
  <div class="row">
    <% @categories.each do |category| %>
      <div class= "col-xs-12 col-sm-6 col-md-3 ">
        <div class="card">
          <div class="card-img" style="width: 100%; height: 180px;">
            <%= cl_image_tag category.picture.path %>
          </div>
          <div class="gradient">
          </div>
          <div class="card-title">
            <%= link_to category.name, category_path(category) %>
          </div>
          <div class="poll-count">
          <p><%= category.polls.size %> battles</p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container-fluid" style="padding: 0px">
  <div class="row" style="margin: 0px">
    <% @category_polls.reverse.each do |poll| %>
    <div class="col-xs-12 col-md-4" style="padding: 0px">
      <div class="cardm">
        <div class="head">
          <h2>
            <% if poll.user.facebook_picture_url? %>
              <%= image_tag poll.user.facebook_picture_url %>
            <% else %>
              <%= cl_image_tag poll.user.picture.path %>
            <% end %>
          </h2>
          <p><%= poll.user.username %></p>
          <h4><%= poll.title %></h4>
        </div>
        <div class="body">
          <%= link_to poll_path(poll) do %>
          <div class="cardc1">
            <div class="clip-left">
              <div class="left-wrapper">
                <%= cl_image_tag poll.responses[0].picture.path%>
              </div>
            </div>
            <div class="clip-right">
              <div class="right-wrapper">
                <%= cl_image_tag poll.responses[1].picture.path %>
              </div>
            </div>
            <% end %>
          </div>
          <div class="foot">
            <div class="box">
              <a href=""><span class="ion-heart"></span> <%= poll.responses.first.votes.size %> Votes</a>
              <a href=""><span class="ion-eye"></span> <%= poll.reviews.size %> Reviews</a>
              <a href=""><span class="ion-chatbox"></span> <%= poll.responses.last.votes.size %> Votes</a>
            </div>
          </div>
        </div>
      </div>
    </div>
      <% end %>
  </div>

</div>
<svg class="clip-svg" width="0" height="0">
  <defs>
  <clipPath id="clip-left-path" clipPathUnits="objectBoundingBox">
  <polygon points="0 0, 0.6 0, 0.4 1, 0 1">
    </clipPath>
    <clipPath id="clip-right-path" clipPathUnits="objectBoundingBox">
    <polygon points="0.6 0, 1 0, 1 1, 0.4 1">
      </clipPath>
      </defs>
    </svg>